
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"F:\Thesis\GUI\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#FFD782")


canvas = Canvas(
    window,
    bg = "#FFD782",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    474.0,
    50.0,
    974.0,
    550.0,
    fill="#EB221E",
    outline="")

canvas.create_rectangle(
    45.0,
    45.0,
    141.0,
    141.0,
    fill="#000000",
    outline="")

canvas.create_text(
    37.0,
    221.0,
    anchor="nw",
    text="BerryScan",
    fill="#000000",
    font=("Inter ExtraBold", 80 * -1)
)

canvas.create_rectangle(
    45.0,
    323.0,
    445.0,
    398.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
