
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"F:\Thesis\GUI\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#FFD782")


canvas = Canvas(
    window,
    bg = "#FFD782",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    63.0,
    182.0,
    961.0,
    687.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    45.0,
    45.0,
    141.0,
    141.0,
    fill="#000000",
    outline="")

canvas.create_text(
    290.0,
    30.0,
    anchor="nw",
    text="Archives",
    fill="#000000",
    font=("Inter ExtraBold", 100 * -1)
)

canvas.create_rectangle(
    1004.0,
    5.0,
    1024.0,
    595.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    0.0,
    537.0,
    1024.0,
    600.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
