
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"F:\Thesis\GUI\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#FFD782")


canvas = Canvas(
    window,
    bg = "#FFD782",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1024.0,
    600.0,
    fill="#FFD782",
    outline="")

canvas.create_text(
    741.0,
    525.0,
    anchor="nw",
    text="CHRISTIAN JEREMIAH I. COMIA",
    fill="#000000",
    font=("Inter ExtraBold", 13 * -1)
)

canvas.create_text(
    399.0,
    525.0,
    anchor="nw",
    text="CRYSTAL KATHERINE I. PARUNGAO",
    fill="#000000",
    font=("Inter ExtraBold", 13 * -1)
)

canvas.create_text(
    107.0,
    525.0,
    anchor="nw",
    text="DR. JOHN PAUL T. CRUZ",
    fill="#000000",
    font=("Inter ExtraBold", 13 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    841.0,
    407.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    512.0,
    407.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    183.0,
    407.0,
    image=image_image_3
)

canvas.create_text(
    70.0,
    178.0,
    anchor="nw",
    text="Detection of CBB-Infested Coffee Berries using YOLOv9\nand the Slicing Aided Hyper Inference Technique",
    fill="#000000",
    font=("Inter ExtraBoldItalic", 32 * -1)
)

canvas.create_text(
    330.0,
    30.0,
    anchor="nw",
    text="Credits",
    fill="#000000",
    font=("Inter ExtraBold", 100 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=45.0,
    y=45.0,
    width=96.0,
    height=96.0
)
window.resizable(False, False)
window.mainloop()
