
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"F:\Thesis\GUI\build\assets\frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x600")
window.configure(bg = "#FFD782")


canvas = Canvas(
    window,
    bg = "#FFD782",
    height = 600,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    2.0,
    0.0,
    1026.0,
    600.0,
    fill="#FFD782",
    outline="")

canvas.create_text(
    70.0,
    260.0,
    anchor="nw",
    text="Detection of CBB-Infested Coffee Berries using YOLOv9\nand the Slicing Aided Hyper Inference Technique",
    fill="#000000",
    font=("Inter ExtraBold", 32 * -1)
)

canvas.create_text(
    252.0,
    30.0,
    anchor="nw",
    text="BerryScan",
    fill="#000000",
    font=("Inter ExtraBold", 100 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=287.0,
    y=485.0,
    width=450.0,
    height=85.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=772.0,
    y=485.0,
    width=225.0,
    height=85.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=27.0,
    y=485.0,
    width=225.0,
    height=85.0
)
window.resizable(False, False)
window.mainloop()
